language: node_js
node_js:
  - node
install:
  - npm i -g npm
  - npm ci
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: o/Ym5fqTwbuCFSkYwnXXUccf2NELi/J0P4zMtmATS/e8r09Pg8bYn5vb6n5U5fkJT3lnhLVEKmvgGnEgE0595DAAoRS2toTk/Gf3QUnwYK1emh9ulzhE7yDUEpok4UjN5YMyp1gMVI9t1a4Bv/Ng/HAzPnMGd4A1w7m1GDeqRGQsWkdSJonFRT8ILYYBhZsaGyrCMTw1Hn2wy264axtOW59ZYluC97053JoiK6YMM4k5+BkvgpIXDy/NAy0kAYB3+M334YxFpiMNJObP7o2M1trUz+hs5T/s4ub1zNEHCVYKR4gWNnFD8hFn/X/lsdG7ixryS99EQrO8PdEjahH0cq6URBRRn64xHvAlAbzu77RkE+P0VK/2katrfc5X9a/gAbKLyGwbKoDKcLCY288iv4p6ZsLsRHUtdjT9+jpLTYN5dV1V7Lu4W45mexk5KHRONWrayUlhaLidi+kj5HftUrRLCkvmSxyo3VTkT0M/uR/5RIU1ci344mP/O2urhUCQZga8eBG+4BC2B+agtZGrLNc0Tc4B1jRJHm0+Hz9JRfq6NG/jAHJU5bfo5UGV2jvxtR+CYIwx0nCHKjENyXXa/FSkPn68hdw24w8q3ey0l/9IhAXddSksngV0x3Lb1Tjie53afYtYDDvi360HMbBTG8Xrf8W9tB92jTmzqle2WF0=
notifications:
  email:
    - travis@nevenall.games
