language: node_js
node_js:
  - node
install:
  - npm i -g npm
  - npm ci
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: nO8BHTQgbCobPJNuKXTyS8nHVc8UwkyXahGAK90zGiC07N8Nqgp7MPe7xFLroLCCUpkOJ6vp/eMDsPV6jfht41Smj3cNK2slD6ki4nfEHADV/QSgf0hyriFrwWvKJOzIt9w/te7BQhc3BX2CEqhWrHXU6d6bEtuFYdNvbQdkrEByJAmkdKbJk7uKX+H2hxVXYTI/liqWLU/KGFd/1zXQ3XOP+LElmhtj7Zj0tfl+ql4nzmSOySTNfSjqZ8hDYtqCm+sgb7Vq/LXKqFlQrLDEMd6vrN26A1C69W6ux22CGGuxBQAEIogsdxomZJa3oUU++InR1LLFltWNohGSLN1sP6ZzR8hFmBEg9BkCTTi6Nye51VsRHrL+o2JbyUSSNNyV20mSSc9obLfH/TiZtP2SCgeusl54FR0j2Si5XRjLiZDgBTh9bkaUEH8pubXXGC813TEfB3f/8Dljij1gZnoLNyG+04eIjzudlUuRE1E9Hx3QNJtrP3gDeT/bmvHBoITFNvDt12jkMcNkAdUhW8w6iYoQd3Q1c7/QcnWQ2vCLtbf53znn8ZyOQpMAapmh8lqF8zPEoj3RJoMI50/B1Zy9oAXpgYdSX91n7Me2mCpf4k/zuRwoIHdQF4fFNgz6yD4XVNIVc6iq8nPguBNRNmnPcbEyoSDGvzIQ0TN3rYSpVUc=
notifications:
  email:
    - travis@nevenall.games
